USE [master]
GO
/****** Object:  Database [GESTAO]    Script Date: 08/02/2023 21:44:08 ******/
CREATE DATABASE [GESTAO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GESTAO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\GESTAO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GESTAO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\GESTAO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GESTAO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GESTAO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GESTAO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GESTAO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GESTAO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GESTAO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GESTAO] SET ARITHABORT OFF 
GO
ALTER DATABASE [GESTAO] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [GESTAO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GESTAO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GESTAO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GESTAO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GESTAO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GESTAO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GESTAO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GESTAO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GESTAO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GESTAO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GESTAO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GESTAO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GESTAO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GESTAO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GESTAO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GESTAO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GESTAO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GESTAO] SET  MULTI_USER 
GO
ALTER DATABASE [GESTAO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GESTAO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GESTAO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GESTAO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GESTAO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GESTAO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GESTAO] SET QUERY_STORE = OFF
GO
USE [GESTAO]
GO
/****** Object:  Table [dbo].[GrupoUsuario]    Script Date: 08/02/2023 21:44:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GrupoUsuario](
	[ID_GRUPUSUARIO] [int] NOT NULL,
	[GrupoUsuario] [varchar](150) NULL,
 CONSTRAINT [PK_GrupoUsuario] PRIMARY KEY CLUSTERED 
(
	[ID_GRUPUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PermisaoGrupoUsuario]    Script Date: 08/02/2023 21:44:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PermisaoGrupoUsuario](
	[COD_PERMISSAO] [int] NOT NULL,
	[COD_GRUPOUSUARIO] [int] NOT NULL,
 CONSTRAINT [PK_PermisaoGrupoUsuario] PRIMARY KEY CLUSTERED 
(
	[COD_PERMISSAO] ASC,
	[COD_GRUPOUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissao]    Script Date: 08/02/2023 21:44:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissao](
	[ID_PERMISSAO] [int] NOT NULL,
	[Descricao] [varchar](150) NULL,
 CONSTRAINT [PK_Permissao] PRIMARY KEY CLUSTERED 
(
	[ID_PERMISSAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 08/02/2023 21:44:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](150) NULL,
	[NomeUsuario] [varchar](150) NULL,
	[CPF] [varchar](15) NULL,
	[Email] [varchar](150) NULL,
	[Senha] [varchar](50) NULL,
	[Ativo] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UsuarioGrupoUsuario]    Script Date: 08/02/2023 21:44:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsuarioGrupoUsuario](
	[COD_USUARIO] [int] NOT NULL,
	[COD_GRUPOUSUARIO] [int] NOT NULL,
 CONSTRAINT [PK_UsuarioGrupoUsuario] PRIMARY KEY CLUSTERED 
(
	[COD_USUARIO] ASC,
	[COD_GRUPOUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PermisaoGrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_PermisaoGrupoUsuario_GrupoUsuario] FOREIGN KEY([COD_GRUPOUSUARIO])
REFERENCES [dbo].[GrupoUsuario] ([ID_GRUPUSUARIO])
GO
ALTER TABLE [dbo].[PermisaoGrupoUsuario] CHECK CONSTRAINT [FK_PermisaoGrupoUsuario_GrupoUsuario]
GO
ALTER TABLE [dbo].[PermisaoGrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_PermisaoGrupoUsuario_Permissao] FOREIGN KEY([COD_PERMISSAO])
REFERENCES [dbo].[Permissao] ([ID_PERMISSAO])
GO
ALTER TABLE [dbo].[PermisaoGrupoUsuario] CHECK CONSTRAINT [FK_PermisaoGrupoUsuario_Permissao]
GO
ALTER TABLE [dbo].[UsuarioGrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_UsuarioGrupoUsuario_GrupoUsuario] FOREIGN KEY([COD_GRUPOUSUARIO])
REFERENCES [dbo].[GrupoUsuario] ([ID_GRUPUSUARIO])
GO
ALTER TABLE [dbo].[UsuarioGrupoUsuario] CHECK CONSTRAINT [FK_UsuarioGrupoUsuario_GrupoUsuario]
GO
ALTER TABLE [dbo].[UsuarioGrupoUsuario]  WITH CHECK ADD  CONSTRAINT [FK_UsuarioGrupoUsuario_Usuario] FOREIGN KEY([COD_USUARIO])
REFERENCES [dbo].[Usuario] ([ID])
GO
ALTER TABLE [dbo].[UsuarioGrupoUsuario] CHECK CONSTRAINT [FK_UsuarioGrupoUsuario_Usuario]
GO
USE [master]
GO
ALTER DATABASE [GESTAO] SET  READ_WRITE 
GO
